---
- name: Decrement Counter
  hosts: shdemo_nuc
  gather_facts: false
  become_user: yes

  vars_prompt: []

  tasks:
    - name: Send GET request to localhost
      uri:
        url: "http://localhost:8180/decrementCounter"
        method: GET
        status_code: 200
      register: api_response
    - name: Display the value of run_script variable
      debug:
        msg: "Value of run_script variable: {{ api_response }}"