# ---
# - name: run my local script
#   hosts: shdemo_nuc
#   gather_facts: false
#   become_user: yes

#   vars_prompt: []

#   tasks:
#     - name: Run the script
#       ansible.builtin.shell: ./script.sh >> output2.txt
#       args:
#         chdir: /home/farooq/test

---
- name: Disable USB Ports for NUC
  hosts: shdemo_nuc
  gather_facts: false
  become_user: yes

  vars_prompt: []

  tasks:
    - name: Send GET request to localhost
      uri:
        url: "http://localhost:8080/disableUSBPorts"
        method: GET
        status_code: 200
      register: api_response