---
- name: run my local script
  hosts: shdemo_rpi
  gather_facts: false
  become_user: yes

  vars_prompt: []

  tasks:
    - name: Run the script
      ansible.builtin.shell: ./script.sh >> output2.txt
      args:
        chdir: /home/shadmin/test
      when: run_script|lower == 'yes'