---
- name: run my local script
  hosts: shdemo_rpi
  gather_facts: false
  become_user: yes
  
  tasks:
    - name: Run the script
      ansible.builtin.shell: ./script.sh >> output.txt
      args:
        chdir: /home/shadmin/test