---
- name: Run the script and display output
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Run script
      shell: |
        echo "____________"
        echo "You have successfully completed your task"
        echo "____________"
      register: script_output

    - name: Display script output
      debug:
        var: script_output.stdout_lines
