---
- name: run my local script
  hosts: laptops
  remote_user: farooque
  become_user: root

  tasks:
    - name: running local script
      command: sh /home/farooque/Desktop/Ansible
      register: script_output

    - name: Display script output
      debug:
        var: script_output.stdout_lines