---
- name: Display
  hosts: shdemo_nuc
  gather_facts: false
  become_user: yes

  vars_prompt: []

  tasks:
    - name: Send GET request to localhost
      uri:
        url: "http://localhost:8180/display"
        method: GET
        status_code: 200
      register: api_response