---
- name: run my local script
  hosts: shdemo-rpi
  
  tasks:
    - name: Run script
      shell: |
        echo "____________"
        echo "You have successfully completed your task"
        echo "____________"
      register: script_output

    - name: Display script output
      debug:
        var: script_output.stdout_lines