---
- name: run my local script
  hosts: shdemo_rpi
  
  tasks:
    - name: Run the script
      ansible.builtin.shell: ./script.sh
      args:
        chdir: /home/shadmin/test
      register: script_output
      changed_when: true
      
    - name: Display script output
      debug:
        var: script_output.stdout_lines